title: Project Bitshift
description: "A project that teaches binary through a hands on #D environment. Our goal is to teach binary for people who don't understand but are willing to learn."
owner_name: Spencer Lyons
github_username: Frogpants
github_repo: "Project-Bitshift" 
baseurl: "/bitshift"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/logintoolkit.md
